### ISSUE TITLE
Desenvolvimento

### ISSUE THREAD

**Issue by gheeenrique** [gabriel-schenato/emaj#3]
Olá, estou iniciando um desenvolvimento com o mesmo objetivo para facilitar as rotinas de um escritório de advocacia. 
Você conseguiu colocar para que seja feito a busca/atualização dos processo automaticamente?

**Comment by GabrielSchenato** [comment]
Boa noite @gheeenrique tudo bem? Desculpa a demora para responder, só agora que vi a issue. Pois então cara não cheguei a fazer porque o projeto aqui é mais simples estou desenvolvendo um protótipo.
Porém para futuro posso pensar nisso.
